# Generated by Django 5.1.4 on 2024-12-29 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_remove_flete_nombre_flete_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flete',
            name='Paquete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flete', to='cliente.paquete'),
        ),
        migrations.AddField(
            model_name='flete',
            name='transportista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fletes', to='cliente.transportista'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.usuario'),
        ),
    ]
