# Generated by Django 5.1.4 on 2024-12-29 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_flete_paquete_flete_transportista_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usuario',
        ),
    ]
