# Generated by Django 5.1.4 on 2024-12-29 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_remove_usuario_groups_and_more'),
        ('core', '0003_usuario_delete_freight_remove_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paquete', to='core.usuario'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
        migrations.RenameField(
            model_name='flete',
            old_name='Paquete',
            new_name='paquete',
        ),
        migrations.AlterField(
            model_name='flete',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fletes', to='core.usuario'),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
