# Generated by Django 5.1.4 on 2024-12-29 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_alter_paquete_usuario_alter_cotizacion_cliente_and_more'),
        ('core', '0003_usuario_delete_freight_remove_user_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
